### ISSUE TITLE
17/5000 It cannot be installed on Ubuntu24.04

### ISSUE THREAD

**Issue by danjuan101** [CLRX/CLRX-mirror#36]
**I tried to build on Ubuntu24.04 but got an error**

/usr/include/CL/cl_gl_ext.h:18:112: note: ‘#pragma message: The extensions in cl_gl_ext.h have been moved into cl_gl.h.  Please include cl_gl.h directly.’
   18 | #pragma message("The extensions in cl_gl_ext.h have been moved into cl_gl.h.  Please include cl_gl.h directly.")
      |                                                                                                                ^
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:422:39: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_0_DEPRECATED’
  422 |         cl_command_queue_properties*) CL_EXT_SUFFIX__VERSION_1_0_DEPRECATED;
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:426:18: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  426 |         cl_int*) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:430:33: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  430 |         size_t, void*, cl_int*) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:433:9: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  433 |         CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:436:38: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  436 |         cl_command_queue, cl_event*) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:439:53: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  439 |         cl_command_queue, cl_uint, const cl_event*) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:442:27: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  442 |         cl_command_queue) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:445:22: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED’
  445 |         const char*) CL_EXT_SUFFIX__VERSION_1_1_DEPRECATED;
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:538:9: error: ‘CLRXpfn_clSetCommandQueueProperty’ does not name a type; did you mean ‘CLRXpfn_clGetCommandQueueInfo’?
  538 |         CLRXpfn_clSetCommandQueueProperty clSetCommandQueueProperty;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         CLRXpfn_clGetCommandQueueInfo
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:540:9: error: ‘CLRXpfn_clCreateImage2D’ does not name a type; did you mean ‘CLRXpfn_clCreateImage’?
  540 |         CLRXpfn_clCreateImage2D clCreateImage2D;
      |         ^~~~~~~~~~~~~~~~~~~~~~~
      |         CLRXpfn_clCreateImage
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:541:9: error: ‘CLRXpfn_clCreateImage3D’ does not name a type; did you mean ‘CLRXpfn_clCreateImage’?
  541 |         CLRXpfn_clCreateImage3D clCreateImage3D;
      |         ^~~~~~~~~~~~~~~~~~~~~~~
      |         CLRXpfn_clCreateImage
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:556:9: error: ‘CLRXpfn_clUnloadCompiler’ does not name a type; did you mean ‘CLRXpfn_clUnloadPlatformCompiler’?
  556 |         CLRXpfn_clUnloadCompiler clUnloadCompiler;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
      |         CLRXpfn_clUnloadPlatformCompiler
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:587:9: error: ‘CLRXpfn_clEnqueueMarker’ does not name a type; did you mean ‘CLRXpfn_clEnqueueTask’?
  587 |         CLRXpfn_clEnqueueMarker clEnqueueMarker;
      |         ^~~~~~~~~~~~~~~~~~~~~~~
      |         CLRXpfn_clEnqueueTask
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:588:9: error: ‘CLRXpfn_clEnqueueWaitForEvents’ does not name a type; did you mean ‘CLRXpfn_clWaitForEvents’?
  588 |         CLRXpfn_clEnqueueWaitForEvents clEnqueueWaitForEvents;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         CLRXpfn_clWaitForEvents
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:589:9: error: ‘CLRXpfn_clEnqueueBarrier’ does not name a type; did you mean ‘CLRXpfn_clEnqueueTask’?
  589 |         CLRXpfn_clEnqueueBarrier clEnqueueBarrier;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
      |         CLRXpfn_clEnqueueTask
/home/primea/CLRX-mirror/clwrapper/DispatchStruct.h:590:9: error: ‘CLRXpfn_clGetExtensionFunctionAddress’ does not name a type; did you mean ‘CLRXpfn_clGetExtensionFunctionAddressForPlatform’?
  590 |         CLRXpfn_clGetExtensionFunctionAddress clGetExtensionFunctionAddress;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         CLRXpfn_clGetExtensionFunctionAddressForPlatform
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:45:51: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_0_DEPRECATED’
   45 |     cl_command_queue_properties * old_properties) CL_EXT_SUFFIX__VERSION_1_0_DEPRECATED;
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:74:58: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_2’
   74 |                                    cl_event * /*event*/) CL_EXT_SUFFIX__VERSION_1_2;
      |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:83:59: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_2’
   83 |                                     cl_event * /*event*/) CL_EXT_SUFFIX__VERSION_1_2;
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:93:56: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_2’
   93 |                                  cl_event * /*event*/) CL_EXT_SUFFIX__VERSION_1_2;
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:103:46: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_2’
  103 |                            cl_event * event) CL_EXT_SUFFIX__VERSION_1_2;
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:112:43: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_2’
  112 |                         cl_event * event) CL_EXT_SUFFIX__VERSION_1_2;
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:122:44: error: expected initializer before ‘CL_EXT_SUFFIX__VERSION_1_2’
  122 |                          cl_event * event) CL_EXT_SUFFIX__VERSION_1_2;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/primea/CLRX-mirror/clwrapper/CLWrapper.h:125:
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:149:26: error: ‘clEnqueueWaitSignalAMD’ was not declared in this scope
  149 | CLRX_CL_INTERNAL_DECLSYM(clEnqueueWaitSignalAMD)
      |                          ^~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:28:58: note: in definition of macro ‘CLRX_CL_INTERNAL_DECLSYM’
   28 | #  define CLRX_CL_INTERNAL_DECLSYM(NAME) extern decltype(NAME) clrx##NAME \
      |                                                          ^~~~
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:149:26: error: ‘clEnqueueWaitSignalAMD’ was not declared in this scope
  149 | CLRX_CL_INTERNAL_DECLSYM(clEnqueueWaitSignalAMD)
      |                          ^~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:28:58: note: in definition of macro ‘CLRX_CL_INTERNAL_DECLSYM’
   28 | #  define CLRX_CL_INTERNAL_DECLSYM(NAME) extern decltype(NAME) clrx##NAME \
      |                                                          ^~~~
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:150:26: error: ‘clEnqueueWriteSignalAMD’ was not declared in this scope; did you mean ‘clrxclEnqueueWaitSignalAMD’?
  150 | CLRX_CL_INTERNAL_DECLSYM(clEnqueueWriteSignalAMD)
      |                          ^~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:28:58: note: in definition of macro ‘CLRX_CL_INTERNAL_DECLSYM’
   28 | #  define CLRX_CL_INTERNAL_DECLSYM(NAME) extern decltype(NAME) clrx##NAME \
      |                                                          ^~~~
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:150:26: error: ‘clEnqueueWriteSignalAMD’ was not declared in this scope; did you mean ‘clrxclEnqueueWaitSignalAMD’?
  150 | CLRX_CL_INTERNAL_DECLSYM(clEnqueueWriteSignalAMD)
      |                          ^~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:28:58: note: in definition of macro ‘CLRX_CL_INTERNAL_DECLSYM’
   28 | #  define CLRX_CL_INTERNAL_DECLSYM(NAME) extern decltype(NAME) clrx##NAME \
      |                                                          ^~~~
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:151:26: error: ‘clEnqueueMakeBuffersResidentAMD’ was not declared in this scope
  151 | CLRX_CL_INTERNAL_DECLSYM(clEnqueueMakeBuffersResidentAMD)
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:28:58: note: in definition of macro ‘CLRX_CL_INTERNAL_DECLSYM’
   28 | #  define CLRX_CL_INTERNAL_DECLSYM(NAME) extern decltype(NAME) clrx##NAME \
      |                                                          ^~~~
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:151:26: error: ‘clEnqueueMakeBuffersResidentAMD’ was not declared in this scope
  151 | CLRX_CL_INTERNAL_DECLSYM(clEnqueueMakeBuffersResidentAMD)
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/InternalDecls.h:28:58: note: in definition of macro ‘CLRX_CL_INTERNAL_DECLSYM’
   28 | #  define CLRX_CL_INTERNAL_DECLSYM(NAME) extern decltype(NAME) clrx##NAME \
      |                                                          ^~~~
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:408:22: error: ‘CLRXpfn_clUnloadCompiler’ does not name a type; did you mean ‘CLRXpfn_clUnloadPlatformCompiler’?
  408 | CLRX_INTERNAL extern CLRXpfn_clUnloadCompiler amdOclUnloadCompiler;
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~
      |                      CLRXpfn_clUnloadPlatformCompiler
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:414:22: error: ‘clEnqueueWaitSignalAMD_fn’ does not name a type
  414 | CLRX_INTERNAL extern clEnqueueWaitSignalAMD_fn amdOclEnqueueWaitSignalAMD;
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:415:22: error: ‘clEnqueueWriteSignalAMD_fn’ does not name a type
  415 | CLRX_INTERNAL extern clEnqueueWriteSignalAMD_fn amdOclEnqueueWriteSignalAMD;
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:416:22: error: ‘clEnqueueMakeBuffersResidentAMD_fn’ does not name a type
  416 | CLRX_INTERNAL extern clEnqueueMakeBuffersResidentAMD_fn amdOclEnqueueMakeBuffersResidentAMD;
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLWrapper.h:418:22: error: ‘CLRXpfn_clGetExtensionFunctionAddress’ does not name a type; did you mean ‘CLRXpfn_clGetExtensionFunctionAddressForPlatform’?
  418 | CLRX_INTERNAL extern CLRXpfn_clGetExtensionFunctionAddress
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      CLRXpfn_clGetExtensionFunctionAddressForPlatform
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:52:1: error: ‘CLRXpfn_clUnloadCompiler’ does not name a type; did you mean ‘CLRXpfn_clUnloadPlatformCompiler’?
   52 | CLRXpfn_clUnloadCompiler amdOclUnloadCompiler = nullptr;
      | ^~~~~~~~~~~~~~~~~~~~~~~~
      | CLRXpfn_clUnloadPlatformCompiler
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:60:1: error: ‘clEnqueueWaitSignalAMD_fn’ does not name a type
   60 | clEnqueueWaitSignalAMD_fn amdOclEnqueueWaitSignalAMD = nullptr;
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:61:1: error: ‘clEnqueueWriteSignalAMD_fn’ does not name a type
   61 | clEnqueueWriteSignalAMD_fn amdOclEnqueueWriteSignalAMD = nullptr;
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:62:1: error: ‘clEnqueueMakeBuffersResidentAMD_fn’ does not name a type
   62 | clEnqueueMakeBuffersResidentAMD_fn amdOclEnqueueMakeBuffersResidentAMD = nullptr;
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:64:1: error: ‘CLRXpfn_clGetExtensionFunctionAddress’ does not name a type; did you mean ‘CLRXpfn_clGetExtensionFunctionAddressForPlatform’?
   64 | CLRXpfn_clGetExtensionFunctionAddress amdOclGetExtensionFunctionAddress = nullptr;
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | CLRXpfn_clGetExtensionFunctionAddressForPlatform
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:97:42: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   97 |     { "clEnqueueMakeBuffersResidentAMD", (void*)clrxclEnqueueMakeBuffersResidentAMD },
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:107:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  107 |     { "clEnqueueWaitSignalAMD", (void*)clrxclEnqueueWaitSignalAMD },
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:108:34: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  108 |     { "clEnqueueWriteSignalAMD", (void*)clrxclEnqueueWriteSignalAMD },
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:299:3: error: too many initializers for ‘_CLRXIcdDispatch::<unnamed struct>’
  299 | } };
      |   ^
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp: In function ‘void clrxWrapperInitialize()’:
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:365:11: error: ‘amdOclUnloadCompiler’ was not declared in this scope; did you mean ‘clrxclUnloadCompiler’?
  365 |         { amdOclUnloadCompiler = (CLRXpfn_clUnloadCompiler)
      |           ^~~~~~~~~~~~~~~~~~~~
      |           clrxclUnloadCompiler
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:365:35: error: ‘CLRXpfn_clUnloadCompiler’ was not declared in this scope; did you mean ‘clrxclUnloadCompiler’?
  365 |         { amdOclUnloadCompiler = (CLRXpfn_clUnloadCompiler)
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                   clrxclUnloadCompiler
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:370:9: error: ‘amdOclGetExtensionFunctionAddress’ was not declared in this scope; did you mean ‘clrxclGetExtensionFunctionAddress’?
  370 |         amdOclGetExtensionFunctionAddress = (CLRXpfn_clGetExtensionFunctionAddress)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         clrxclGetExtensionFunctionAddress
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:370:46: error: ‘CLRXpfn_clGetExtensionFunctionAddress’ was not declared in this scope; did you mean ‘clrxclGetExtensionFunctionAddress’?
  370 |         amdOclGetExtensionFunctionAddress = (CLRXpfn_clGetExtensionFunctionAddress)
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                              clrxclGetExtensionFunctionAddress
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:382:9: error: ‘amdOclEnqueueWaitSignalAMD’ was not declared in this scope; did you mean ‘clrxclEnqueueWaitSignalAMD’?
  382 |         amdOclEnqueueWaitSignalAMD = (clEnqueueWaitSignalAMD_fn)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |         clrxclEnqueueWaitSignalAMD
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:382:39: error: ‘clEnqueueWaitSignalAMD_fn’ was not declared in this scope; did you mean ‘clrxclEnqueueWaitSignalAMD’?
  382 |         amdOclEnqueueWaitSignalAMD = (clEnqueueWaitSignalAMD_fn)
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                       clrxclEnqueueWaitSignalAMD
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:384:9: error: ‘amdOclEnqueueWriteSignalAMD’ was not declared in this scope; did you mean ‘clrxclEnqueueWriteSignalAMD’?
  384 |         amdOclEnqueueWriteSignalAMD = (clEnqueueWriteSignalAMD_fn)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         clrxclEnqueueWriteSignalAMD
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:384:40: error: ‘clEnqueueWriteSignalAMD_fn’ was not declared in this scope; did you mean ‘clrxclEnqueueWriteSignalAMD’?
  384 |         amdOclEnqueueWriteSignalAMD = (clEnqueueWriteSignalAMD_fn)
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        clrxclEnqueueWriteSignalAMD
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:386:9: error: ‘amdOclEnqueueMakeBuffersResidentAMD’ was not declared in this scope; did you mean ‘clrxclEnqueueMakeBuffersResidentAMD’?
  386 |         amdOclEnqueueMakeBuffersResidentAMD = (clEnqueueMakeBuffersResidentAMD_fn)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         clrxclEnqueueMakeBuffersResidentAMD
/home/primea/CLRX-mirror/clwrapper/CLInternals.cpp:386:48: error: ‘clEnqueueMakeBuffersResidentAMD_fn’ was not declared in this scope; did you mean ‘clrxclEnqueueMakeBuffersResidentAMD’?
  386 |         amdOclEnqueueMakeBuffersResidentAMD = (clEnqueueMakeBuffersResidentAMD_fn)
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                clrxclEnqueueMakeBuffersResidentAMD

**Comment by matszpk** [comment]
I recommend to disable CLWrapper by adding -DNO_CLWRAPPER=ON to cmake command. CLwrapper are obsolete.

**Comment by danjuan101** [comment]
@matszpk Thank you for your help. It's very useful to me
